update build script

diff --git a/widget/server/server.init b/widget/server/server.init
--- a/widget/server/server.init
+++ b/widget/server/server.init
@@ -8,10 +8,16 @@
 
 # ALWAYS MAKE SURE THIS FILE IS SAVED WITH UNIX LINE ENDINGS (LF)!
 
-# If you want to use the subtitle search, you must set your OpenSubtitles.com credentials here
+# If you want to use the subtitle search, you must set your OpenSubtitles.com API key here
+OPENSUBTITLESKEY=""
+# Optionally also set credentials for higher download limits
 OPENSUBTITLESUSER=""
 OPENSUBTITLESPASSWORD=""
-OPENSUBTITLESKEY=""
+
+
+# If you want to use the Jackett provider, you must set the API address and API key here
+JACKETTADDRESS=""
+JACKETTKEY=""
 
 # If you want to use the nCore provider, you must set your credentials here
 NCOREUSER=""
@@ -20,10 +26,6 @@ NCOREPASSWORD=""
 # If you want to use the iNSANE provider, you must set your credentials here
 INSANEUSER=""
 INSANEPASSWORD=""
-
-# If you want to use the Jackett provider, you must set the API address and API key here
-JACKETTADDRESS=""
-JACKETTKEY=""
 
 # Specify the torrent storage memory size in MBs
 # 128 MB should work for H series TVs, older models may need to go lower
@@ -39,7 +41,6 @@ UPSPEED="$3"
 
 SERVERDIR="/mtd_rwcommon/widgets/user/WhiteRaven/server"
 SERVERPATH="/mtd_rwcommon/widgets/user/WhiteRaven/server/wrserver"
-TAA="/mtd_rwcommon/widgets/user/WhiteRaven/server/wrserver.taa"
 
 check_processor()
 {
@@ -57,36 +58,42 @@ start_wrserver()
 {
 	empty_cache
 	SERVERSTATUS=$(ps -ef | grep wrserver | grep -v grep)
+
 	if [ "$SERVERSTATUS" == "" ]; then
 		echo "Trying To Start White Raven Server..."
+
 		cd "$SERVERDIR"
 		set_swappiness
-		nice -n +19 ./wrserver -background -storagetype="memory" -memorysize="$MEMORYSIZE" -downrate="$DOWNSPEED" -uprate="$UPSPEED" -osuser "$OPENSUBTITLESUSER" -ospassword "$OPENSUBTITLESPASSWORD" -osapikey "$OPENSUBTITLESKEY" -ncoreuser "$NCOREUSER" -ncorepassword "$NCOREPASSWORD" -insaneuser "$INSANEUSER" -insanepassword "$INSANEPASSWORD" -jackettaddress "$JACKETTADDRESS" -jackettkey "$JACKETTKEY"
+
+		nice -n +19 ./wrserver \
+			-background \
+			-storagetype="memory" \
+			-memorysize="$MEMORYSIZE" \
+			-downrate="$DOWNSPEED" \
+			-uprate="$UPSPEED" \
+			-osuser "$OPENSUBTITLESUSER" \
+			-ospassword "$OPENSUBTITLESPASSWORD" \
+			-osapikey "$OPENSUBTITLESKEY" \
+			-jackettaddress "$JACKETTADDRESS" \
+			-jackettkey "$JACKETTKEY" \
+			-ncoreuser "$NCOREUSER" \
+			-ncorepassword "$NCOREPASSWORD" \
+			-insaneuser "$INSANEUSER" \
+			-insanepassword "$INSANEPASSWORD"
+
 		echo "White Raven Server Is Started!"
 	else
 		echo "White Raven Server Is Already Running!"
 	fi
 }
 
-start_or_decompress_wrserver()
+start_wrserver_if_present()
 {
 	if [ -e "$SERVERPATH" ]; then
-		chmod 755 $SERVERPATH
+		chmod 755 "$SERVERPATH"
 		start_wrserver
 	else
-		if [ -e "$TAA" ]; then
-			echo "Trying To Decompress White Raven Server..."
-			cd "$SERVERDIR"
-			cat wrserver.t* | tar -xvzf -
-			if [ -e "$SERVERPATH" ]; then
-				echo "White Raven Server Is Decompressed!"
-				start_wrserver
-			else
-				echo "White Raven Server Decompression Failed!"
-			fi
-		else
-			echo "One Or More Compressed White Raven Server Files Not Found!"
-		fi
+		echo "White Raven Server Not Found!"
 	fi
 }
 
@@ -100,6 +107,7 @@ stop_wrserver()
 check_status()
 {
 	SERVERSTATUS=$(ps -ef | grep wrserver | grep -v grep)
+
 	if [ "$SERVERSTATUS" != "" ]; then
 		echo "White Raven Server Is Running!"
 	else
@@ -110,6 +118,7 @@ check_status()
 set_swappiness()
 {
 	SWAPPINESS=$(sysctl -n vm.swappiness)
+
 	if [ $SWAPPINESS -gt 30 ]; then
 		echo "Set Swappiness Value To 30!"
 		sysctl -w vm.swappiness=30
@@ -121,19 +130,19 @@ empty_cache()
 	sync && echo 3 > /proc/sys/vm/drop_caches
 }
 
-case $1 in 
+case $1 in
 	start)
-	check_processor
-	start_or_decompress_wrserver
-	;;
+		check_processor
+		start_wrserver_if_present
+		;;
 	stop)
-	stop_wrserver
-	;;
+		stop_wrserver
+		;;
 	status)
-	check_status
-	;;
+		check_status
+		;;
 	*)
-	echo "Usage: $0 {start|stop|status} downspeed upspeed" 1>&2
-	exit 0
-	;;
+		echo "Usage: $0 {start|stop|status} downspeed upspeed" 1>&2
+		exit 0
+		;;
 esac
